server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xahhy/tw-todo-config-service
          search-paths: todo-micro-service-config
          timeout: 60
  profiles:
    active: dev