server:
  port: 8082
spring:
  application:
    name: userService
  datasource:
    url: jdbc:mysql://mysql:3307/todo_user?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 123456