server:
  port: 8088
  context-path: /api

zuul:
  sensitiveHeaders:
  routes:
    user:
      serviceId: userService
      path: /users/**
      stripPrefix: false
    login:
      serviceId: userService
      path: /login/**
      stripPrefix: false
    todo:
      serviceId: todoService
      path: /todos/**
      stripPrefix: false
    tags:
      serviceId: todoService
      path: /tags/**
      stripPrefix: false

spring:
  cloud:
    consul:
      discovery:
        health-check-path: /api/health

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000