server:
  port: 8088
  context-path: /api

zuul:
  sensitiveHeaders:
  routes:
    user:
      serviceId: userService
#      url: http://localhost:8082/user
      path: /users/**
      stripPrefix: false
    login:
#      url: http://localhost:8082/login
      path: /login/**
      serviceId: userService
      stripPrefix: false
    todo:
#      url: http://localhost:8080/todos
      serviceId: todoService
      path: /todos/**
      stripPrefix: false
    tags:
      url: http://localhost:8080/tags
      path: /tags/**

spring:
  cloud:
    consul:
      discovery:
        health-check-path: /api/health